name: Build And Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v2 # Copy files from repository to docker container so the next uploadandscan action can access them. 
      with:
        path: folder_to_upload/*.war # Wildcards can be used to filter the files copied into the container. See: https://github.com/actions/upload-artifact
    - uses: veracode/veracode-uploadandscan-action@master # Run the uploadandscan action. Inputs are described above.
      with:
        filepath: 'folder_to_upload/'
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'
        createsandbox: 'true'
        sandboxname: 'SANDBOXNAME'
        scantimeout: 15
        exclude: '*.js'
        include: '*.war'
        criticality: 'VeryHigh'
